Repository avahi/avahi, pull requests merged in 2023-01, with the labels that each got.

#330 Avoid infinite-loop in avahi-daemon by handling HUP event in client_work
  avahi-daemon/simple-protocol.c
Labels: bug, important

#73 avahi-daemon: fix SIGHUP/SIGUSR1 race condition at startup
  avahi-daemon/main.c
Labels: bug

#312 fix QT3 build
  avahi-qt/Makefile.am
Labels: bug

#202 Two small fixes to issues discovered by static analysis
  avahi-client/browser.c
  avahi-daemon/chroot.c
Labels: bug

#381 Fix encoding of avahi-common/domain.h to be UTF-8
  avahi-common/domain.h
Labels: documentation

#427 dbus: deny SetHostName via org.freedesktop.Avahi.Server2 as well
  avahi-daemon/avahi-dbus.conf.in
Labels: bug

#418 CI: turn on CIFuzz
  .github/workflows/cifuzz.yml
Labels: CI

#376 dbus: Use non-deprecated installation path
  configure.ac
Labels: bug, important

#405 configure.ac: fix -Wstrict-prototypes
  configure.ac
Labels: bug

#306 Logic for p2p on tunnels incorrectly requires IFF_MULTICAST (#305)
  avahi-core/iface-linux.c
  avahi-core/iface-pfroute.c
Labels: bug
