Repository avahi/avahi, pull requests merged in 2023-04, with the labels that each got.

#447 Update Russian translation
  po/ru.po
Labels: localization

#281 Include build-db in tarball releases
  service-type-database/Makefile.am
Labels: enhancement

#435 fix typo
  docs/TODO
  examples/client-browse-services.c
  examples/client-publish-service.c
  examples/core-browse-services.c
  examples/core-publish-service.c
Labels: documentation

#292 Load distribution name from /etc/os-release
  avahi-core/domain-util.c
Labels: enhancement

#434 fix memory leak in wide area lookup
  avahi-core/wide-area.c
Labels: bug

#380 Typo fixes
  avahi-common/rlist.h
  avahi-gobject/ga-entry-group.c
  man/avahi.service.5.xml.in
Labels: bug, documentation

#404 Fix document for avahi-daemon.conf and avahi-publish
  man/avahi-daemon.conf.5.xml.in
  man/avahi-publish.1.xml.in
Labels: documentation

#282 avahi-discover: Don't decode unicode strings, only bytestrings
  avahi-python/avahi-discover/avahi-discover.py
Labels: bug

#253 Fix spelling mistake: whith to with
  avahi-common/defs.h
  avahi-core/probe-sched.c
Labels: documentation

#366 Do not disable timeout cleanup on watch cleanup
  avahi-common/simple-watch.c
Labels: bug

#39 Fix not publishing entries if a probing interface is removed.
  avahi-core/announce.c
Labels: bug, important

#369 avahi-discover: Escape strings substituted into Pango markup
  avahi-python/avahi-discover/avahi-discover.py
Labels: bug

#320 close txt-record markups in examples in man
  man/avahi.service.5.xml.in
Labels: documentation
