Repository avahi/avahi, pull requests merged in 2023-09, with the labels that each got.

#466 Minor text updates to avahi-daemon.8.xml.in
  man/avahi-daemon.8.xml.in
Labels: documentation

#450 Correct error DBusGMainLoop in avahi-bookmarks
  avahi-python/avahi-bookmarks.in
  avahi-python/avahi-discover/avahi-discover.py
Labels: bug, python

#465 libdns_sd: Fix off-by-one error when copying program name in buffer
  avahi-compat-libdns_sd/warn.c
Labels: bug

#457 Ensure each label is at least one byte long
  avahi-common/domain-test.c
  avahi-common/domain.c
Labels: bug, important

#480 [common] bail out when escaped labels can't fit into ret
  avahi-common/domain.c
  fuzz/fuzz-domain.c
Labels: bug

#468 Emit the ServiceResolver Found/Failure signals at the correct time
  avahi-core/resolve-service.c
Labels: bug
