Repository avahi/avahi, pull requests merged in 2024-11, with the labels that each got.

#648 Translations update from Fedora Weblate
  po/LINGUAS
  po/ca.po
  po/kab.po
  po/oc.po
  po/zh_CN.po
Labels: localization, postponed

#656 Extend doxygen dns.h and wide-area.h API
  Makefile.am
  avahi-core/dns.h
  avahi-core/wide-area.h
Labels: documentation

#659 Randomize transaction IDs in wide area queries
  avahi-core/wide-area.c
  configure.ac
Labels: bug, important
