Repository avahi/avahi, pull requests merged in 2024-02, with the labels that each got.

#556 Update description for enable-wide-area to mention impact for avahi-resolve-address
  man/avahi-daemon.conf.5.xml.in
  man/avahi-resolve.1.xml.in
Labels: documentation, squash-on-merge

#565 smoke-test: cover sync address/hostname/service resolvers
  .github/workflows/build.sh
  .github/workflows/smoke-tests.sh
Labels: CI

#429 Increase max hostname specified in simple-protocol
  avahi-daemon/simple-protocol.c
Labels: bug, needs-rebase, needs-tests

#566 smoke-test: pass overly long hostname to RESOLVE-HOSTNAME
  .github/workflows/smoke-tests.sh
Labels: CI

#541 ci: build avahi on aarch64, i386, ppc64le, s390x, x86_64 on PRs
  .packit.yml
Labels: CI

#567 ci: build avahi on various arches on commits too
  .packit.yml
Labels: CI

#569 libdns_sd: Use allocator with memory set to zero
  avahi-compat-libdns_sd/compat.c
Labels: compat-libdns_sd

#575 smoke-test: unicast responses
  .github/workflows/build.sh
  .github/workflows/smoke-tests.sh
Labels: CI
