Repository avahi/avahi, pull requests merged in 2024-03, with the labels that each got.

#580 man: be more specific about host-name-from-machine-id
  avahi-daemon/avahi-daemon.conf
  man/avahi-daemon.conf.5.xml.in
Labels: documentation

#585 CI: lint GH Actions
  .github/workflows/build.yml
  .github/workflows/linter.yml
Labels: CI

#586 CI: add an action sending data to Coverity Scan
  .github/workflows/coverity.sh
  .github/workflows/coverity.yml
Labels: CI

#587 Report fatal error when UI file were not loaded
  avahi-discover-standalone/main.c
Labels: enhancement
