Repository avahi/avahi, pull requests merged in 2024-09, with the labels that each got.

#639 Translations update from Fedora Weblate
  po/fi.po
Labels: localization

#640 Translations update from Fedora Weblate
  po/es.po
Labels: localization

#642 Enable style checker in cppcheck in Packit OpenScanHub configurations
  .packit.yml
Labels: CI

#645 build-system: switch to localedir
  avahi-common/Makefile.am
  avahi-python/avahi-discover/Makefile.am
  avahi-ui/Makefile.am
  configure.ac
Labels: localization, build-system
