Repository avahi/avahi, pull requests merged in 2024-08, with the labels that each got.

#624 po: add avahi.pot
  po/avahi.pot
Labels: localization, CI

#625 Translations update from Fedora Weblate
  po/fr.po
Labels: localization

#627 README: point to the Fedora Weblate instance
  README
Labels: documentation, CI

#626 Translations update from Fedora Weblate
  po/fa.po
  po/ja.po
  po/ko.po
  po/pt_BR.po
Labels: localization

#628 Translations update from Fedora Weblate
  po/ka.po
Labels: localization

#629 Translations update from Fedora Weblate
  po/tr.po
Labels: localization

#631 Translations update from Fedora Weblate
  po/sl.po
Labels: localization

#609 Increase length limit on input lines.
  avahi-daemon/ini-file-parser.c
Labels: reflector, squash-on-merge

#634 Translations update from Fedora Weblate
  po/LINGUAS
  po/fur.po
Labels: localization
